package: spamschutz
version: '2.0-beta4'
author: 'Alexander Walther, FriendsOfREDAXO'
supportpage: https://github.com/friendsofredaxo/spamschutz

requires:
    redaxo: "^5.13"
    packages:
        yform: "^4"
    php:
        version: ">=7.4,<9"

page:
    hidden: true

pages:
    yform/spam_protection:
        title: "Spamschutz"
        subpages:
            settings:
                title: "Einstellungen"
                perm: spamschutz
            docs:
                title: "Dokumentation"
            log:
                title: "Log"
                perm: spamschutz

default_config:
    block_session_time: 2
    block_form_time: 5
    block_threshold_limit: 10
    block_threshold_time: 300
    block_tlds: ".ru"
    #   block_geoip: 0

    whitelist_user: 1
    whitelist_ips: "127.0.0.1"
    whitelist_ycom_user: 1

    block_stop_forum_spam: 0
#   notification_email: ''
